project:
  type: website

website:
  title: "Ketsia Guichard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - research.qmd
      - teaching.qmd
      - others.qmd
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

