project:
  output-dir: docs/fr

website:
  title: "Ketsia Guichard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - href: research.qmd
        text: Recherche
      - href: softwares.qmd
        text: Logiciels
      - href: teaching.qmd
        text: Enseignement
      - href: others.qmd
        text: Autres activités
    right:
      - href: ../fr
        text: Français
      - href: ../en
        text: English
    search: false
  page-footer: 
    left: Ce site a été construit à l'aide de [Quarto](https://quarto.org/) - dernière mise à jour Juin 2024.
    right: 
     - icon: github
       href: https://github.com/KetsiaGuichard/academic-page

lang: fr

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header: 
      file: header.html
editor: visual
