::: {.content-visible when-profile="french"}
::: {.callout-tip icon="false" collapse="false" appearance="minimal"}
# Année 2024-2025

##### Digisport (ENSAI, ENS Rennes, Université Rennes 2)

-   Cours magistral - Remise à niveau en probabilités et statistiques pour le master Sciences du Numérique et Sport (22h - Niveau M1)

##### Université de Rennes

-   TP - Outils informatiques (Algorithmie) en L1 Mathématiques et application (24h)
:::

::: {.callout-tip icon="false" collapse="false" appearance="minimal"}
# Année 2023-2024

##### Digisport (ENSAI, ENS Rennes, Université Rennes 2)

-   Cours magistral - Remise à niveau en probabilités et statistiques pour le master Sciences du Numérique et Sport (22h - Niveau M1)

##### Université de Rennes

-   TP - Outils informatiques (Algorithmie) en L1 Mathématiques et application (24h)

##### Université de Rennes 2

-   TD intégré - Mathématiques pour les sciences humaines et sociales en L1 AES (24h)

##### ENSAI

-   Présidence de jury - projet statistique de deuxième année
:::

::: {.callout-tip icon="false" collapse="true" appearance="minimal"}
# Année 2022-2023

##### ENSAI

-   Cours magistral - Statistique exploratoire, visualisation de données et data-storytelling (24h - Master Spécialisé)

-   TD - Chaîne de Markov (18h - Niveau M1)

-   TP - Statistique descriptive avec SAS (30h - Niveau L3)

-   TP - Introduction à la programmation objet avec Python (42h - Niveau L3)

-   Accompagnement de projet - Projet statistique sur données réelles (36h - 8 groupes - Niveau L3)

-   Présidence de jury - projet statistique de deuxième année
:::

::: {.callout-tip icon="false" collapse="true" appearance="minimal"}
# Année 2021-2022

##### ENSAI

-   Cours magistral - Datavisualisation et data-storytelling (18h - Master Spécialisé)

-   Présidence de jury - projet statistique de deuxième année
:::
:::

::: {.content-visible when-profile="english"}
::: {.callout-tip icon="false" collapse="false" appearance="minimal"}
# Academic Year 2024-2025

##### Digisport (ENSAI, ENS Rennes, Université Rennes 2)

-   Lecture - Probability and Statistics Review for the Master's in Digital Sciences and Sports (22 hours - M1)

##### Université de Rennes

-   Practical Work - Computer Tools (Algorithmics) (24h - L1)
:::


::: {.callout-tip icon="false" collapse="false" appearance="minimal"}
# Academic Year 2023-2024

##### Digisport (ENSAI, ENS Rennes, Université Rennes 2)

-   Lecture - Probability and Statistics Review for the Master's in Digital Sciences and Sports (22 hours - M1)

##### Université de Rennes

-   Practical Work - Computer Tools (Algorithmics) (24h - L1)

##### Université de Rennes 2

-   Lecture & Tutorial - Mathematics for Social Sciences (24 hours - L1)

##### ENSAI

-   Jury President - Second-Year Statistics Project
:::

::: {.callout-tip icon="false" collapse="true" appearance="minimal"}
# Academic Year 2022-2023

##### ENSAI

-   Lecture - Exploratory Statistics, Data Visualization, and Data Storytelling (24 hours - Specialized Master's)

-   Tutorial - Markov Chain (18 hours - M1)

-   Practical Work - Introduction to Object-Oriented Programming with Python (42 hours - L3)

-   TP - Introduction à la programmation objet avec Python (42h - L3)

-   Project Guidance - Statistical Project on Real Data (36 hours - 8 groups - L3)

-   Jury President - Second-Year Statistics Project
:::

::: {.callout-tip icon="false" collapse="true" appearance="minimal"}
# Academic Year 2021-2022

##### ENSAI

-   Lecture - Data Visualization and Data Storytelling (18 hours - Specialized Master's)

-   Jury President - Second-Year Statistics Project
:::
:::

